### ISSUE TITLE
Update Hackage cabal file for binary-0.8.8

### ISSUE THREAD

**Issue by maksbotan** [hyraxbio/hyraxAbif#3]
Hi,

The `hyraxAbif.cabal` file on Hackage does not quite match the one in this repo. In particular, it has dependency on `binary  0.8.8.8`, preventing it to compile on latest Stackage nightly.

Please make a new revision. Also note, that `binary` dependency in the **test** component is fixed on Hackage, but not in the repo, so the two things must be synchronized...

**Comment by andrevdm** [comment]
Thanks, I'll update shortly

**Comment by andrevdm** [comment]
Fixed in https://hackage.haskell.org/package/hyraxAbif-0.2.3.27

 - 29fe40797bf1965c33047810a544943c9001bd0c => latest version
 - 1b5268d17e5f5b5238e95414baeb8d211a828140 => deps fixes

**Comment by maksbotan** [comment]
Thanks!
