### ISSUE TITLE
Update cabal file to allow QuickCheck-2.14

### ISSUE THREAD

**Issue by maksbotan** [hyraxbio/hyraxAbif#4]
Hi,

Latest Stackage nightly (2021-01-02) includes `QuickCheck-2.14.2`, which is disallowed by `hyraxAbif`'s cabal file. Please either make a new version of make a Hackage revision to allow it.

Thanks!

**Comment by andrevdm** [comment]
Hi,

Fixed with a hackage revision, `bytestring >= 0.10.8.2 && < 0.10.13.0`.

Tested with stackage nightly nightly-2021-01-03

Andre

**Comment by maksbotan** [comment]
Thanks, it works :)
