### ISSUE TITLE
Hackage releases

### ISSUE THREAD

**Issue by maksbotan** [hyraxbio/hyraxAbif#6]
Hi!

Can you please release the latest version to Hackage? As far as I see, 0.2.4.1 in master is compatible with GHC 9.2, however latest version on Hackage is still 0.2.3.27.

**Comment by andrevdm** [comment]
0.2.4.2 pushed and released to hackage.

It should support Stack LTS 20.7 and GHC 9.2.5 support.

I'll close this, please comment or reopen if you have any issues
